### ISSUE TITLE
downloading the dataset

### ISSUE THREAD

**Issue by shashikantdeepak** [leftthomas/SRGAN#107]
how to download the data set outside china as the Baidu repo is unavailable to access.

**Comment by CatalinOAlexandru** [comment]
Hi. I also had problems downloading the datasets. But I managed it by using the [instructions here](https://gist.github.com/mfiro/b0bdf5f4054a34c36bf3a8e6d9bf5397).

I also uploaded the 2 datasets linked in the README to google drive. 
[Here is the link](https://drive.google.com/drive/folders/1PuGKTrmtqrzsRDv9XUTHh8NCZUArjpoV?usp=sharing)

**Comment by DHjun** [comment]
@CatalinOAlexandru Could you plz check the Google drive link? i can not access it. Thank you.
