### ISSUE TITLE
Multiplication by 2 in TV loss implementation

### ISSUE THREAD

**Issue by Caffetaria** [leftthomas/SRGAN#108]
In the [original SRGAN paper](https://arxiv.org/pdf/1609.04802.pdf) there doesn't seem to be any mention of multiplying the TV Loss by 2. Is there a reason for multiplying by 2 in the code in [loss.py](https://github.com/leftthomas/SRGAN/blob/master/loss.py) ?

`return self.tv_loss_weight * 2 * (h_tv / count_h + w_tv / count_w) / batch_size`

**Comment by HuXia7157** [comment]
> 

what is tv loss

**Comment by leftthomas** [comment]
@Caffetaria in this repo, I have tried some different loss hyper-parameters, it seems this version is better, you could try by yourself to get better result.
