### ISSUE TITLE
Set14 dataset miss Set14_003.img!!!

### ISSUE THREAD

**Issue by Jackson-LIMU** [leftthomas/SRGAN#110]
![G RZ~MRXI@ 5ETT}R{ 55PR](https://user-images.githubusercontent.com/75259876/129322256-07138872-2094-42f1-9597-c10a41a207d5.png)
as shown before

**Comment by leftthomas** [comment]
@Jackson-LIMU you could add that image to your dataset, as I remember, it's a gray image, so I remove that. You could add that and then change code to be compatible with gray image.
