### ISSUE TITLE
About the parameters of the pytorch_ssim.ssim()  function

### ISSUE THREAD

**Issue by Fuca-Fuda** [leftthomas/SRGAN#119]
Hello

I encountered a mistake in the following position.

---> 84   batch_ssim = pytorch_ssim.ssim(sr, hr).item()

TypeError: conv2d() received an invalid combination of arguments - got (Tensor, Tensor, padding=float, groups=int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)

The format of the input data is as follows：
torch.Size([4, 3, 256, 256])
torch.float32
torch.Size([4, 3, 256, 256])
torch.float32

According to my investigation, the function currently only accepts a pair of pictures as input, not the entire epoch, so it is not available in the case of validation set batchsize > 1.

Thanks in advance !

**Comment by leftthomas** [comment]
yes, you should for loop each image to get the ssim value.
