### ISSUE TITLE
训练、测试的结果色彩偏红

### ISSUE THREAD

**Issue by sunyclj** [leftthomas/SRGAN#123]
您好，我的训练集是VID2K的800张数据，验证集输出色彩正常，取别的数据（1080,1920,3）进行x2超分后，色彩偏红，请问可以从哪些方面分析原因呢？

**Comment by leftthomas** [comment]
maybe you could try to change the loss weight.

**Comment by sunyclj** [comment]
请问色调偏红的原因是什么呢？loss的权重应该如何调节？



---原始邮件---
发件人: "Hao ***@***.***&gt;
发送时间: 2021年12月16日(周四) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [leftthomas/SRGAN] 训练、测试的结果色彩偏红 (Issue #123)




 
maybe you could try to change the loss weight.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leftthomas** [comment]
you should find the reason by yourself, this repo is just a re-implement of `SRGAN`.
