### ISSUE TITLE
Does anyone know how to set the upscale_factor as 3?

### ISSUE THREAD

**Issue by PinRuei** [leftthomas/SRGAN#124]
I try to train a model using upscale factor x3, but in the code it seems to use 2, 4, 8 scale.
Is there any possibility to training a x3 model?
Thanks.

**Comment by liu1216** [comment]
Sorry to bother you, but do you know how to train the X3 model？
Thanks.

**Comment by PinRuei** [comment]
> Sorry to bother you, but do you know how to train the X3 model？ Thanks.

Ｉ have changed 
block8 = [UpsampleBLock(64, 3) for _ in range(1)]
in https://github.com/leftthomas/SRGAN/blob/bed685fd4f48cfcecfc5b3a728aa0d220b1a11c0/model.py#L24

**Comment by liu1216** [comment]
Thank you very much. It helped me a lot！
