### ISSUE TITLE
What should I do to test with my own dataset

### ISSUE THREAD

**Issue by YANYANYEAH** [leftthomas/SRGAN#13]
Test with my own dataset

**Comment by leftthomas** [comment]
@YANYANYEAH You should read `readme.md` carefully.

**Comment by YANYANYEAH** [comment]
Thanks a lot , but my dataset does not have target pictures . So when I run test_benchmark.py , it will comes error.

**Comment by leftthomas** [comment]
@YANYANYEAH , ` test_benchmark.py` will test the performance of some open image datasets, if you have no targets, how do you  compute the performance?
