### ISSUE TITLE
Transform methods

### ISSUE THREAD

**Issue by hmtrii** [leftthomas/SRGAN#132]
Hi, 
SRGAN paper's authors said that they scaled the range of the HR images to [−1, 1]. However, I wonder that your code do not implement this transform. Could you explain the reason? Thank you

**Comment by leftthomas** [comment]
@hmtrii  look at these code, we scale images to [0, 1]
https://github.com/leftthomas/SRGAN/blob/bed685fd4f48cfcecfc5b3a728aa0d220b1a11c0/data_utils.py#L20

https://github.com/leftthomas/SRGAN/blob/bed685fd4f48cfcecfc5b3a728aa0d220b1a11c0/model.py#L38

**Comment by leftthomas** [comment]
@hmtrii you could try that scale to [-1, 1] or [0, 1] will no any effort to the results.
