### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by pip2go** [leftthomas/SRGAN#139]
This error is hapenen when 【train.py】is run，I was really puzzled that I cannot find the solutions. Plese help me.Thanks! 
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'data/DIV2K_train_HR'

**Comment by leftthomas** [comment]
@pip2go you should run that on Linux, the Windows use different path way.

**Comment by pip2go** [comment]
I have solved my problem.Thank you,you are really kindness!

**Comment by pip2go** [comment]
Could you tell me where is my trained video.I just cannot fint it on the same directory.Is it means that it replaced by the new trined viedo.Hower,it is the same quality as before.Could you give me some tips?
