### ISSUE TITLE
test_benchmark error

### ISSUE THREAD

**Issue by SamehOmri** [leftthomas/SRGAN#149]
when excute testbenchmark.py
File "/content/drive/MyDrive/SRGAN/test_benchmark.py", line 33, in
test_set = TestDatasetFromFolder('data/test/', upscale_factor=UPSCALE_FACTOR)
File "/content/drive/MyDrive/SRGAN/data_utils.py", line 85, in init
self.lr_filenames = [join(self.lr_path, x) for x in listdir(self.lr_path) if is_image_file(x)]
FileNotFoundError: [Errno 2] No such file or directory: 'data/test//SRF_2/data/'

**Comment by leftthomas** [comment]
@SamehOmri the error has told you, you have no data, you should first download data and train the model.

**Comment by SamehOmri** [comment]
I have data
