### ISSUE TITLE
Missing log function is the loss?

### ISSUE THREAD

**Issue by YOCB** [leftthomas/SRGAN#15]
In the [discriminator loss](https://github.com/leftthomas/SRGAN/blob/e1f9fdb7dbbb7a023ddbd19340e82101ae9147fa/train.py#L75-L77) and [generator loss](https://github.com/leftthomas/SRGAN/blob/e1f9fdb7dbbb7a023ddbd19340e82101ae9147fa/loss.py#L19), isn't there a log function missing before the mean?
In the [SRGAN paper](https://arxiv.org/pdf/1609.04802.pdf) in eq. 2 there is a log function.

**Comment by leftthomas** [comment]
@YOCB I changed that in my code, if you want implement the same loss, then you should change it by yourself.
