### ISSUE TITLE
How to change the function of increasing resolution to increasing the scale of the generated image

### ISSUE THREAD

**Issue by catyoyo** [leftthomas/SRGAN#150]
Hello authors, I think SRGAN is somewhat in line with my research, and I would like to modify the functionality of SRGAN so that it can generate larger-scale images instead of increasing resolution.For example, a 2m*2m rock image is generated based on a 2cm*2cm rock training dataset.What code should I modify to meet my needs? Thank you

**Comment by leftthomas** [comment]
@catyoyo you should read the code to change the function by yourself

**Comment by catyoyo** [comment]
I am terribly sorry, my expression was not adequate, and I fear I may have caused you to misunderstand my meaning. I deeply dislike being the kind of person who simply demands that others complete everything for me. Rather, I humbly hope that you, in your wisdom and experience, might be able to provide me with some high-level guidance and direction. As a beginner, I know I am prone to wandering down many wrong paths, and it is only through the gracious and benevolent instruction of those who have gone before that I can hope to find a clear way forward, rather than stumbling blindly in the dark.I am truly and deeply grateful for any insights or perspectives you may be willing to graciously share with me. I humbly hope that you could provide me with some guiding direction on the paths I should consider for making modifications or improvements to the code.
