### ISSUE TITLE
May I ask within what range D (x) and D (G (z)) are maintained to indicate that the model has been trained？

### ISSUE THREAD

**Issue by HaoLongfei-1** [leftthomas/SRGAN#152]
The result of running your code shows that D (x) and D (G (z)) remain around 1, doesn't that mean the discriminator is too weak?

**Comment by lieyandadao** [comment]
G is too weak , D too strong， you can follow the paper's method, pretrain the G with MSEloss, this may solve the problem.

**Comment by leftthomas** [comment]
@lieyandadao you could make a PR, the code for this repo was written by me several years ago, it's been too long
