### ISSUE TITLE
How to use this this for 8 upscaling factor?

### ISSUE THREAD

**Issue by Vishal2188** [leftthomas/SRGAN#18]
I want to super resolute the images with 8 upscaling factor. How can I do this?

**Comment by zahra-anvari** [comment]
Hi @Vishal2188 ,
I've trained the network with upscaling factor of 8, but at test time I get this error : RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "block8.2.bias", "block8.2.weight". 
	Unexpected key(s) in state_dict: "block8.3.weight", "block8.3.bias", "block8.2.conv.weight", "block8.2.conv.bias", "block8.2.prelu.weight". 
have you by any chanced had this error or know how to fix it? thanks.
