### ISSUE TITLE
Alternative download links?

### ISSUE THREAD

**Issue by EKami** [leftthomas/SRGAN#2]
Hello,
Is it possible that you upload the train/val/test datasets to something else than baidu? I'm not chinese and each time I try to download what appears to be the dataset I actually download an executable file. I don't want to install anything on my computer, just download the datasets. Thanks.

**Comment by leftthomas** [comment]
@EKami you could go to the original datasets websites to download the datasets, then make your own datasets, I also given the websites links on readme.

**Comment by AkhilSinghRana** [comment]
Could you also add how the skeleton of custom data folder should look like. I can't download the data from Baidu either. It asks to download an exe(don't really want to do that).

**Comment by leftthomas** [comment]
@AkhilSinghRana https://github.com/leftthomas/SRGAN/blob/e1f9fdb7dbbb7a023ddbd19340e82101ae9147fa/data_utils.py#L82
