### ISSUE TITLE
how do you get the PSNR and SSIM value

### ISSUE THREAD

**Issue by babyjia** [leftthomas/SRGAN#20]
Sorry to bother you that , I am wondering how you calculated these evaluation indicators? Do you use ｔhe function already written in the MATLAB or you just write by yourself？ If you write by yourself,will you upload to github?
waiting for your reply ~ thx

**Comment by leftthomas** [comment]
@babyjia it have already been uploaded, do you read my code carefully? Do you notice the `pytorch_ssim` dir?
