### ISSUE TITLE
would it effects the final result that feeding a input in size of 96x96 to pretrained model while the pretrained model was trained with 224x224 on imagenet ?

### ISSUE THREAD

**Issue by pangwong** [leftthomas/SRGAN#22]
Hi,
    I found the pretrained model you use is ```torchvision.models.vgg ``` whose ```input size``` should be ```224x224```. And when you deploy the model to calculate the feature map, you feed HR_image whose size is ```96x96``` directly to the pretrained model. Obvious the two sizes are mismatched though there is no error occurs when train. 
Would the slight difference influences the final result, i.e the feature maps of input image in vgg higher layer are not well represented ?

**Comment by leftthomas** [comment]
@pangwong you could try it, I have not tested it.
