### ISSUE TITLE
Output image

### ISSUE THREAD

**Issue by sonal-bansal** [leftthomas/SRGAN#26]
Hi,
I've trained my SRResnet on DIV2K and during testing I've tried SET14.
Here is my resulting image
![output](https://user-images.githubusercontent.com/33753404/52631192-1fa77480-2ee4-11e9-9563-0098ec5160c2.png)

My image is having this weird green/blue pixels  around sharp and bright regions.Is this because my model isn't working well or do i need to perform further processing on my output?
What do u suggest?

**Comment by leftthomas** [comment]
@sonal-bansal you should change your loss function, such that add the weight of Perception Loss

**Comment by mnoiy** [comment]
> Hi,
> I've trained my SRResnet on DIV2K and during testing I've tried SET14.
> Here is my resulting image
> ![output](https://user-images.githubusercontent.com/33753404/52631192-1fa77480-2ee4-11e9-9563-0098ec5160c2.png)
> 
> My image is having this weird green/blue pixels around sharp and bright regions.Is this because my model isn't working well or do i need to perform further processing on my output?
> What do u suggest?

hey，I have the same question，how do you handle it?
