### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by chaoyueziji** [leftthomas/SRGAN#27]
Thanks your works, but I have a simple question that how to keep the same size of input image with output image. I found your result is a same size picture that input,output,origin not enlarge the picture. 
![image](https://user-images.githubusercontent.com/8329766/55167779-90f96900-51ac-11e9-8a29-2eea9f526150.png)

**Comment by leftthomas** [comment]
@chaoyueziji the output is not same size as input, this  image you showed is concated and resized, you can find related code to product this image in my `save image` part
