### ISSUE TITLE
why D(x) and D(G(z)) estimate all images 1?

### ISSUE THREAD

**Issue by YueXiNPU** [leftthomas/SRGAN#31]
![VOC12](https://user-images.githubusercontent.com/34571270/57070154-eb409900-6d19-11e9-9bd8-a7033d901da8.png)

Recently, I visualize the training stage of Loss in SRGAN.
I use the same code and same dataset (16700 images) from VOC12.
However, I get the training stage as above shown.
What wrong with the experiments?

**Comment by leftthomas** [comment]
It is not wrong, the GAN training is unstable, and the loss of D model has no reference meaning, if you want to loss more stable, you should control the training stage to make sure the G model can catch up D model

**Comment by YueXiNPU** [comment]
Thank you very much.
