### ISSUE TITLE
Loading pretrained weights from "epochs/" directory

### ISSUE THREAD

**Issue by khnaba** [leftthomas/SRGAN#34]
Hi Thomas,

We are trying to load and test your pre-trained weights for the generator network found in epoch/ directory. However, it doesn't seem to load for us. Could the model have changed in between after you saved the weights? If so, are you able to provide the latest weights that apply to the current master branch?

Thanks.
-Naba

**Comment by khnaba** [comment]
Could this patch have introduced the difference in network?
https://github.com/leftthomas/SRGAN/commit/4ac34861b1cd042cc49e75dc7ac366947b088ab0#diff-93ff136fae812392eb0f68d1ce89b7fe

**Comment by leftthomas** [comment]
@khnaba YES, it introduces difference, after that, I have not trained the model again, that patch just to make sure the model as same as the paper.
