### ISSUE TITLE
How to calculate psnr on y_channel ITU-R BT.2020, standard

### ISSUE THREAD

**Issue by ninesun127** [leftthomas/SRGAN#35]
calculate the psnr on y_channel using y,_,_=Image.open('').convert('YCbCr').split()but that refers to the JPEG, and not the ITU-R BT.2020, standard,
this result is different from the paper matlab version.can we solve it?

**Comment by leftthomas** [comment]
I haven't notice that, just use the python method to compute PSNR, it gives the compute formula, that according that, we could realize that.
