### ISSUE TITLE
test_video doesn't work

### ISSUE THREAD

**Issue by zahra-anvari** [leftthomas/SRGAN#37]
I tried the test_video script and it gets stuck at cv2.VideoWriter line. My input video's a 15sec mp4, RGB video I also tried other formats like avi. I'm running the code on an ubuntu system with 1 GPU, python3, opencv 4.1.0-pre installed.
I really appreciate any help.

**Comment by leftthomas** [comment]
@zahra-anvari you should install `opencv` by Conda, and make sure your CPU could load the model or you GPU can load.

**Comment by zahra-anvari** [comment]
Thank you so much!
