### ISSUE TITLE
Hi, how to deal with one-channel(i mean gray scale) images with SRGAN's network?

### ISSUE THREAD

**Issue by CaptainEven** [leftthomas/SRGAN#4]

**Comment by leftthomas** [comment]
@CaptainEven change the in channel of the network to 1, and other misc

**Comment by CaptainEven** [comment]
Hi, i changed input channels from 3 to 1 in   Generator and Discriminator but an error occured like this:  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 67, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Given groups=1, weight[64, 3, 3, 3], so expected input[8, 1, 88, 88] to have 3 channels, but got 1 channels instead
got any idea or suggestion?

**Comment by leftthomas** [comment]
@CaptainEven Because you only change that, you should also change other misc, not just only there, you should change the image preprocessing code, visualization code, some save image code and PSNR computation code, etc.

**Comment by apyrros** [comment]
In data_utils.py simply add .convert('RGB') to convert a grayscale image to RGB and add three channels. It is a built-in function in PIL.


class TrainDatasetFromFolder(Dataset):
    def __init__(self, dataset_dir, crop_size, upscale_factor):
        super(TrainDatasetFromFolder, self).__init__()
        self.image_filenames = [join(dataset_dir, x) for x in listdir(dataset_dir) if is_image_file(x)]
        crop_size = calculate_valid_crop_size(crop_size, upscale_factor)
        self.hr_transform = train_hr_transform(crop_size)
        self.lr_transform = train_lr_transform(crop_size, upscale_factor)

    def __getitem__(self, index):
        hr_image = self.hr_transform(Image.open(self.image_filenames[index]).convert('RGB'))
        lr_image = self.lr_transform(hr_image)
        return lr_image, hr_image

    def __len__(self):
        return len(self.image_filenames)


class ValDatasetFromFolder(Dataset):
    def __init__(self, dataset_dir, upscale_factor):
        super(ValDatasetFromFolder, self).__init__()
        self.upscale_factor = upscale_factor
        self.image_filenames = [join(dataset_dir, x) for x in listdir(dataset_dir) if is_image_file(x)]

    def __getitem__(self, index):
        hr_image = Image.open(self.image_filenames[index]).convert('RGB')
        w, h = hr_image.size
        crop_size = calculate_valid_crop_size(min(w, h), self.upscale_factor)
        lr_scale = Resize(crop_size // self.upscale_factor, interpolation=Image.BICUBIC)
        hr_scale = Resize(crop_size, interpolation=Image.BICUBIC)
        hr_image = CenterCrop(crop_size)(hr_image)
        lr_image = lr_scale(hr_image)
        hr_restore_img = hr_scale(lr_image)
        return ToTensor()(lr_image), ToTensor()(hr_restore_img), ToTensor()(hr_image)
