### ISSUE TITLE
Error in loading the data

### ISSUE THREAD

**Issue by ritesh2212** [leftthomas/SRGAN#40]
Hi, 
I'm getting the following error while loading the data given in your train.py file. I can't even find the solution for this error. Can you help?
 
![image](https://user-images.githubusercontent.com/45995263/59976096-7719c780-95dd-11e9-93e6-64386a4ebaaf.png)

**Comment by ritesh2212** [comment]
found solution.

**Comment by zahra-anvari** [comment]
> found solution.

Hi,
I got stuck with the same error. Can you please share your solution?
Thank you so much!

**Comment by ritesh2212** [comment]
Change crop_size default value. Given 88, checks with 40 or 60. 40 works for me.

**Comment by zahra-anvari** [comment]
@ritesh2212 Fixed, thank you so much for your reply!
