### ISSUE TITLE
Error when I use 1-channel image file

### ISSUE THREAD

**Issue by mohammad-saber** [leftthomas/SRGAN#41]
Hi,

I am using SRGAN "test_image.py" for a 1-channel image file. I see the following error:

    "RuntimeError: Given groups=1, weight of size [64, 3, 9, 9], expected input[1, 1, 128, 128] to have 3 channels, but got 1 channels instead"

Please let me know how I can use SRGAN for 1-channel image.

If I train network from scratch with a dataset containing only 1-channel images, can I use this new model for 1-channel images?

**Comment by leftthomas** [comment]
@mohammad-saber  you should change input channel of model to 1 and change data loader code to load 1 channel image
