### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by zahra-anvari** [leftthomas/SRGAN#42]
Hi everyone, 
I'm getting the following error while loading the data given in your train.py file. I can't even find the solution for this error. Does anyone know how to fix it? I appreciate any help/suggestions.
![issue](https://user-images.githubusercontent.com/27265281/60544631-09048d00-9cce-11e9-91c2-6984ad5113c8.png)

**Comment by leftthomas** [comment]
@zahra-anvari your image's size is less than the crop size, then it will report the error, so make sure your image size can be cropped. Or you could change the preprocess code about image resize and crop

**Comment by zahra-anvari** [comment]
@leftthomas Fixed! Thanks a lot for the quick reply!

**Comment by NicoLivesey** [comment]
Hi @zahra-anvari what fix did you do to prevent this error ? Thanks in advance

**Comment by zahra-anvari** [comment]
> Hi @zahra-anvari what fix did you do to prevent this error ? Thanks in advance

Hi @NicoLivesey you need to use a smaller crop_size, 60 and 40 worked for me, default's 70 but some of the images are smaller than that.

**Comment by NicoLivesey** [comment]
Thank you very much that was my first intuition. The default value is now 88, maybe you should think about lowering it a bit since some image in VOC2012 are smaller than that @leftthomas. 70 worked for me.
