### ISSUE TITLE
GPU RAM exploding on validation

### ISSUE THREAD

**Issue by NicoLivesey** [leftthomas/SRGAN#43]
Hi, first thank you for this awesome implementation.

Here's my problem, I translated your code in Pytorch 1.1, achieved a complete training on VOC2012 in order to reproduce your work. Everything worked fine. 
Now I added some images to the dataset (like 5000 more) mostly scene text image, I want to improve the model performance on text reconstruction. The first epoch training works fine, I use the same batch size as before and then when the validation come the GPU memory explode after some iterations (19% of the validation loop). 

I know the flag `volatile=True` is no longer used and I replaced it by `torch.no_grad()` which worked well on VOC2012.

Do you know what might go wrong with it ?
Thank you for your help !

**Comment by leftthomas** [comment]
maybe somewhere you need detach tensor, but you haven't detach it, just copy it, then gpu will explode

**Comment by siahuat0727** [comment]
@NicoLivesey Did you fix you problem?
I have the same problem when training with DIV2K，the code run out of memory after a few epochs. I only  replaced `volatile=True`  by `torch.no_grad()` and use different datasets only.

**Comment by siahuat0727** [comment]
I've fixed it by adding `with torch.no_grad():` to the entire validation for loop, probably some operations like `.mean()`   save the entire calculation graph, rather than just the values.
[Reference](https://discuss.pytorch.org/t/cuda-memory-leakage/33970/3)
