### ISSUE TITLE
Some matters that need further discussion?

### ISSUE THREAD

**Issue by ninesun127** [leftthomas/SRGAN#44]
1.RGB->YCbCr
has many different standard,while the past papers's transfer style is different from the Image.convert function.

2.pillow vs matlab
matlab's resize function to produce the LR image is different from the pillow Image.resize(image.bicubic).
I have test the LR image pillow and DIV2K provided,some pixel value is different

3.when test the benchmark,the crop size should be the rectange rather than squre(valid_crop_size)

4.I will extend my greatest the appreciation if you can offer an complete code that achieve the same metric on benchmark dataset  as SR paper

**Comment by leftthomas** [comment]
@ninesun127 this is unofficial implement, so I only code SRGAN as I comprehend
