### ISSUE TITLE
can't reproduce 4x scaling

### ISSUE THREAD

**Issue by makslevental** [leftthomas/SRGAN#48]
with default params i can't reproduce your psnr and ssim on any of the test sets. did you adjust lr, momentum, decay, etc for 4x case?

**Comment by leftthomas** [comment]
@makslevental , no, I haven't, you could try more times

**Comment by makslevental** [comment]
@leftthomas which version of pytorch are you using?

**Comment by leftthomas** [comment]
@makslevental at that time, is 0.3

**Comment by makslevental** [comment]
@leftthomas thank you very much :)

**Comment by makslevental** [comment]
@leftthomas did you ever notice the discriminator overpowering the generator? i my g_score get much much smaller than my d_score (over time) and then of course the psnr/ssim never improves. this doesn't happen on 2x but it does on 4x and 8x.

**Comment by leftthomas** [comment]
@makslevental this is the common problem of GAN

**Comment by makslevental** [comment]
@leftthomas yes i know. i'm asking you how you overcame it

**Comment by leftthomas** [comment]
@makslevental this repo is reimplementation of SRGAN, I just code like the paper said, I haven't try to improve it.
