### ISSUE TITLE
Test image

### ISSUE THREAD

**Issue by hailehong** [leftthomas/SRGAN#5]
Hi @leftthomas 
Thank you for your work. I have tested the code. Below, the left image is the original, the right image is the result image. The boundaries seem not be so smooth. Could you give me some clues about this? 
Thank you!
![sr-4](https://user-images.githubusercontent.com/15852617/36706018-8d64230a-1b9a-11e8-94ce-69f574b455ff.png)

**Comment by leftthomas** [comment]
Duplicate of #3
