### ISSUE TITLE
Runtime error after train

### ISSUE THREAD

**Issue by Wazted** [leftthomas/SRGAN#53]
Hi, I have an error when I load the trained model.

I did the train with my own dataset but when I try to test it I got this error.

`
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "block8.1.weight", "block8.1.bias".
	Unexpected key(s) in state_dict: "block8.2.weight", "block8.2.bias", "block8.1.conv.weight", "block8.1.conv.bias", "block8.1.prelu.weight".
`

**Comment by leftthomas** [comment]
@Wazted look code carefully, the model should trained with specific up scale, you can't train a model with upscale 2 and used with upscale 4 or 8.
