### ISSUE TITLE
D loss & D(X)&D(G(X)) is "1"

### ISSUE THREAD

**Issue by mnoiy** [leftthomas/SRGAN#54]
我训练到第6个epoch开始Loss_D，D(x)， D(G(z)) 就不再变化了，一直是1，只有lossG还在变化，，请问是什么原因呢？
输出的结果如下：
[12/100] Loss_D: 1.0000 Loss_G: 0.0071 D(x): 1.0000 D(G(z)): 1.0000:

**Comment by leftthomas** [comment]
@mnoiy 
Duplicate of #31

**Comment by mnoiy** [comment]
> @mnoiy
> Duplicate of #31

thanks~
