### ISSUE TITLE
Issue when inferencing 

### ISSUE THREAD

**Issue by nareshmungpara** [leftthomas/SRGAN#60]
I have trained the model on mu data and training when well on 1080Ti.

When I am passing testing images to model then it is giving me out of memory error.
Error is as following,
`RuntimeError: CUDA out of memory. Tried to allocate 878.00 MiB (GPU 0; 10.92 GiB total capacity; 9.48 GiB already allocated; 544.06 MiB free; 1.17 MiB cached)
`
input image size is [2436,1476]

Please suggest some way to run the model in this image.

If possible then please suggest some way to do inferencing on 2 or more GPUs.

**Comment by leftthomas** [comment]
@nareshmungpara  the image is large, you should use a more powerful GPU, such as V100
