### ISSUE TITLE
Perceptual loss with wrong input image scale?

### ISSUE THREAD

**Issue by jshi31** [leftthomas/SRGAN#62]
Hi, in the code [perceptual loss](https://github.com/leftthomas/SRGAN/blob/a8ee7c79309becb2f099aae30b67242f5355cb23/loss.py#L21), the output image is scaled in [0, 1], however, the input image for VGG should be normalized by mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225] according to [torchvision](https://pytorch.org/docs/master/torchvision/models.html). Seems you didn't normalize the image.

**Comment by leftthomas** [comment]
@jshi31 this may have a little impact on the results, you could try to add this normalization and compare the performance, if this can make a big impact, please tell me, and I'll add this operation.
