### ISSUE TITLE
one epoch killed

### ISSUE THREAD

**Issue by yeyewen** [leftthomas/SRGAN#68]
![image](https://user-images.githubusercontent.com/37136363/79035917-7d714280-7bf5-11ea-9d90-199fc6d32c3f.png)
![image](https://user-images.githubusercontent.com/37136363/79035926-9679f380-7bf5-11ea-94d4-c524081a209b.png)
@leftthomas 
Hi , I tried to change batchsize to 8, it didn't work. 
Any ideas?

**Comment by yeyewen** [comment]
I solved it ,Thanks!

**Comment by simplew2011** [comment]
no sloved.
![image](https://user-images.githubusercontent.com/66729924/210134489-aa82c22f-e706-4522-9902-f17ee3d3d597.png)
