### ISSUE TITLE
Image normalization

### ISSUE THREAD

**Issue by manurare** [leftthomas/SRGAN#72]
Hi,

I was wondering about this quote on the SRGAN paper:
"_We scaled the range of the LR input images to [0, 1] and for the HR images to [−1, 1]. The MSE loss was thus calculated on images of intensity range [−1, 1]. VGG feature maps were also rescaled by a factor of 1/12.75 to obtain VGG losses of a scale that is comparable to the MSE loss. This is equivalent to multiplying Equation 5 with a rescaling factor of ≈ 0.006_"

As far as I have seen in the code this consideration is not contemplated. Does it affect on anything in terms of results or that same weight can be kept for the perception loss even though the samples are not normalized to [-1,1]?

**Comment by leftthomas** [comment]
I just rescale the images to [0, 1], I think it will not affect the results, you could try to change that.
