### ISSUE TITLE
Runtimeerror when running train.py

### ISSUE THREAD

**Issue by lucasc400** [leftthomas/SRGAN#74]
Hi there,
I encountered the following error when I ran train.py. I tried both locally (Windows 10 with pytorch v1.5.1) and on Google Colab and both yielded the same error. Could you provide any thoughts as to why this occurred? Thanks.

Traceback (most recent call last):
  File "train.py", line 88, in <module>
    g_loss.backward()
  File "C:\Users\User\anaconda3\envs\SR\lib\site-packages\torch\tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\User\anaconda3\envs\SR\lib\site-packages\torch\autograd\__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by ali-zafari** [comment]
@lucasc400 

I faced the same error. By adding the two lines below, it was fixed:
```python
.
.
.
############################
# (2) Update G network: minimize 1-D(G(z)) + Perception Loss + Image Loss + TV Loss
###########################
netG.zero_grad()
############################################################
## The two lines below are added to prevent runetime error! ##
fake_img, _ = netG(z)
fake_out = netD(fake_img).mean()
############################################################
g_loss = generator_criterion(fake_out, fake_img, real_img)
.
.
.
```

**Comment by meeng251** [comment]
Hi @ali-zafari @developer0hye 
I tried to add the two lines same to you in train.py but have the error like this:

  File "train.py", line 90, in <module>
    fake_img, _ = netG(z)
ValueError: not enough values to unpack (expected 2, got 1)

Could you give me solution for this problem ? Thank you !

**Comment by ali-zafari** [comment]
@meeng251 
Oh I'm sorry. I made a mistake in the code snippet above. I had customized the generator for myself.
By the way, I repeated the correct code below: (The point is that the generator should send out only ONE output)

```python
.
.
.
############################
# (2) Update G network: minimize 1-D(G(z)) + Perception Loss + Image Loss + TV Loss
###########################
netG.zero_grad()
############################################################
## The two lines below are added to prevent runetime error! ##
fake_img = netG(z)
fake_out = netD(fake_img).mean()
############################################################
g_loss = generator_criterion(fake_out, fake_img, real_img)
.
.
.
```

**Comment by meeng251** [comment]
Hi @ali-zafari , according to your fixed code, I found it's duplicate 2 lines of code:
- fake_img = netG(z)
- fake_out = netD(fake_img).mean()
 
So you keep it or delete it if duplicate ?

            ############################
            # (2) Update G network: minimize 1-D(G(z)) + Perception Loss + Image Loss + TV Loss
            ###########################
            netG.zero_grad()
            ############################################################
            ## The two lines below are added to prevent runetime error! ##
            fake_img = netG(z)
            fake_out = netD(fake_img).mean()
            ############################################################
            g_loss = generator_criterion(fake_out, fake_img, real_img)
            g_loss.backward()
            
            fake_img = netG(z)
            fake_out = netD(fake_img).mean()
               
            optimizerG.step()

**Comment by ali-zafari** [comment]
@meeng251 
They are not duplicate. the former is the fake image produced from generator and the latter is the decision of discriminator about the produced image. So keep both.
