### ISSUE TITLE
Ask about the Benchmark problem

### ISSUE THREAD

**Issue by meeng251** [leftthomas/SRGAN#76]
Hi @leftthomas @developer0hye 
I trained with DIV2K dataset and for Benchmark.py I put 3 samples of Urban100 dataset in path /data/test/SRF_4/data and I have the problem: 

[testing benchmark datasets]:   0% 0/3 [00:00<?, ?it/s]test_benchmark.py:43: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  lr_image = Variable(lr_image, volatile=True)
test_benchmark.py:44: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  hr_image = Variable(hr_image, volatile=True)
Traceback (most recent call last):
  File "test_benchmark.py", line 50, in <module>
    mse = ((hr_image - sr_image) ** 2).data.mean()
RuntimeError: The size of tensor a (250) must match the size of tensor b (4096) at non-singleton dimension 3
[testing benchmark datasets]:   0% 0/3 [00:01<?, ?it/s]

Could you hint me solution, I need to study more :( Thank you!

**Comment by leftthomas** [comment]
@meeng251 Google it, not always propose issues, you need more familiar with python and pytorch.

**Comment by meeng251** [comment]
@leftthomas  @developer0hye 
I checked MSE expression is right accroding to your code: mse = ((hr_image - sr_image) ** 2).data.mean()

But it still has an error:
- File "test_benchmark.py", line 50, in
mse = ((hr_image - sr_image) ** 2).data.mean()
RuntimeError: The size of tensor a (250) must match the size of tensor b (4096) at non-singleton dimension 3

I don't know why, can you explain to me? Thank you!

NOTE: Train with DIV2K and Set 15 test
