### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by peizhouhuang** [leftthomas/SRGAN#79]
Hi,

I run this code by Pytorch 1.6

When I run to g_loss.backward(), it came out "one of the variables needed for gradient computation has been modified by an inplace operation" error. I don't know how to solve it.

So, can I move the "fake_img" and "fake_out" before calculating the g_loss? Like below:

            netG.zero_grad()
            fake_img = netG(z)
            fake_out = netD(fake_img).mean()
            g_loss = generator_criterion(fake_out, fake_img, real_img)
            g_loss.backward()

            optimizerG.step()

Thanks.

**Comment by leftthomas** [comment]
@peizhouhuang #57

**Comment by yulonghui** [comment]
it works：
replace  .mean() by torch.mean() in the 79 line in train.py
`            # fake_out = netD(fake_img).mean()
            fake_out = torch.mean(netD(fake_img))`

**Comment by yulonghui** [comment]
it works：
replace .mean() by torch.mean() in the 79 line in train.py

`# fake_out = netD(fake_img).mean()`
`fake_out = torch.mean(netD(fake_img))`

**Comment by jackkwok** [comment]
@peizhouhuang: I ran into the same crash with Pytorch 1.7.  Have you solved it?

**Comment by peizhouhuang** [comment]
> @peizhouhuang: I ran into the same crash with Pytorch 1.7. Have you solved it?

You can try to replace .mean() by torch.mean() in the 79 line in train.py 
fake_out = netD(fake_img).mean() 
fake_out = torch.mean(netD(fake_img))

**Comment by jackkwok** [comment]
@peizhouhuang : Thanks for your suggestion but I am still getting the same error.  I replaced mean() with torch.mean in 3 places:

`
            netD.zero_grad()
            real_out = torch.mean(netD(real_img))
            fake_out = torch.mean(netD(fake_img))
            d_loss = 1 - real_out + fake_out
            d_loss.backward(retain_graph=True)
            optimizerD.step()

            ############################
            # (2) Update G network: minimize 1-D(G(z)) + Perception Loss + Image Loss + TV Loss
            ###########################
            #with torch.autograd.set_detect_anomaly(True):
            netG.zero_grad()
            g_loss = generator_criterion(fake_out, fake_img, real_img)
            g_loss.backward()

            fake_img = netG(z)
            fake_out = torch.mean(netD(fake_img))

            optimizerG.step()
`

**Comment by peizhouhuang** [comment]
> @peizhouhuang : Thanks for your suggestion but I am still getting the same error. I replaced mean() with torch.mean in 3 places:
> 
> `
> netD.zero_grad()
> real_out = torch.mean(netD(real_img))
> fake_out = torch.mean(netD(fake_img))
> d_loss = 1 - real_out + fake_out
> d_loss.backward(retain_graph=True)
> optimizerD.step()
> ############################
> # (2) Update G network: minimize 1-D(G(z)) + Perception Loss + Image Loss + TV Loss
> ###########################
> #with torch.autograd.set_detect_anomaly(True):
> netG.zero_grad()
> g_loss = generator_criterion(fake_out, fake_img, real_img)
> g_loss.backward()
> 
> ```
>         fake_img = netG(z)
>         fake_out = torch.mean(netD(fake_img))
> 
>         optimizerG.step()
> ```
> 
> `
Try this, replace original code from line 86 to 94
            netG.zero_grad()
            fake_img = netG(z)
            fake_out = netD(fake_img).mean()
            g_loss = generator_criterion(fake_out, fake_img, real_img)
            g_loss.backward()

            optimizerG.step()

**Comment by DrRyanHuang** [comment]
@peizhouhuang Thx!!!
