### ISSUE TITLE
KeyError: 'img'

### ISSUE THREAD

**Issue by kinyminh99** [leftthomas/SRGAN#80]
Hello, I'm student and this is the first time i've run your benchmark.py and have a problem like this: 

[testing benchmark datasets]:   0% 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "test_benchmark.py", line 66, in <module>
    results[image_name.split('_')[0]]['psnr'].append(psnr)
KeyError: 'img'

I put 5 data to test include Set15, Set14, Urban100, BSD100 and Sunhays80 in my path data/test but I don't know why. Could you explain me about this problem ? Thank you !

@leftthomas  @developer0hye @mukulkhanna  @anant15

**Comment by leftthomas** [comment]
@kinyminh99 use debug and check your images name
