### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by jackkwok** [leftthomas/SRGAN#84]
Thanks for the project.  I ran into immediate crash when running the training script.  Any idea how to fix it?

I have pytorch 1.7.

`
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    g_loss.backward()
  File "/home/ext/.local/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ext/.local/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
`

**Comment by leftthomas** [comment]
@jackkwok use the corresponding version of PyTorch as `readme` stated
