### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### ISSUE THREAD

**Issue by zZFh** [leftthomas/SRGAN#89]
Hi, Thank for your work! I have encountered a problem when I was run your code.
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by leftthomas** [comment]
@zZFh 
Duplicate of #84

**Comment by SuperStacie** [comment]
Actually you can simply do optimizerD.step() and optimizerG.step()  after both d_loss.backward and g_loss.backward to avoid this error.
