### ISSUE TITLE
Input image error 

### ISSUE THREAD

**Issue by gunahn** [leftthomas/SRGAN#97]
Hi, thank you for making nice repo for SRGAN. I would like to use this repo for my own research. I would like to use for my knee X-ray images. 

However, I got this error message. At the moment, the input images are 512*512 gray images. 

_RuntimeError: Given groups=1, weight of size [64, 3, 9, 9], expected input[64, 1, 22, 22] to have 3 channels, but got 1 channels instead_

How am I supposed to change the shape of input image? Thank you:)

**Comment by leftthomas** [comment]
@gunahn you should be more familiar with PyTorch
