### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by StephanHannsi** [leftthomas/SRGAN#98]
Hi,
when training the model the ram usage goes up constantly (like 20GB after some epochs) until I crashes. I tracked the error to this loop: train.py line 117 "for val_lr, val_hr_restore, val_hr in val_bar:"
Any idea why this is the case?
I am using VS Code

**Comment by leftthomas** [comment]
@StephanHannsi check your PyTorch version is 0.4, and use better GPU or small batch size
