### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### ISSUE THREAD

**Issue by xshone** [leftthomas/SRGAN#99]
When i start training, this error occurred. How can i solve this?
Waiting for replies. Thanks.

`
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
`

Environment:

torch                      1.7.1+cu110
torchvision             0.8.2+cu110
opencv-python      4.1.2.30

**Comment by leftthomas** [comment]
@xshone #89
